services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - "./.env"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - ./database/config:/var/lib/postgresql/data